[package]
name = "aipo.ui"
version = "0.1.0"
entry = "src/lib.aipo"
authors = ["Aipo Core Team <core@aipo-lang.org>"]
description = "Universal Declarative Multiplatform UI Framework with Taffy Layout and Pluggable Renderers (Skia, WebGL, TUI)"
license = "MIT"
repository = "https://github.com/poppy-team/aipo-lang"

targets = ["js", "native"]
