[package]
name = "aipo-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "High-Level Intermediate Representation and early desugaring passes for Aipo"
publish = false

[lints]
workspace = true

[dependencies]
aipo-source = { path = "../aipo-source" }
aipo-diagnostics = { path = "../aipo-diagnostics" }
aipo-ast = { path = "../aipo-ast" }
serde = { workspace = true }

[dev-dependencies]
aipo-syntax = { path = "../aipo-syntax" }
